<?php  
if(isset($_SESSION['userRole']) && $_SESSION['userRole'] !== 'superAdmin' && $_SESSION['userRole'] !== 'admin'):
  include  $_SERVER['DOCUMENT_ROOT'].'/views/404.php';
  return;
endif;
 include  $_SERVER['DOCUMENT_ROOT'].'/views/components/header.phtml'; ?>
<style>
    input:focus:required:invalid {border: 1px solid red;}
    input:required:valid { border: 1px solid #d9dee3; }
    select:focus:required:invalid {border: 1px solid red;}
    select:required:valid { border: 1px solid #d9dee3; }
    textarea:focus:required:invalid {border: 1px solid red;}
    textarea:required:valid { border: 1px solid #d9dee3; }
</style>
<link rel="stylesheet" href="/views/assets/css/selectize.css"/>
      

      <!-- Content wrapper -->
      <div class="content-wrapper">

        <!-- Content -->
        
          <div class="container-xxl flex-grow-1 container-p-y">
            
            
<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Sales/</span> Add Sale</h4>

<!-- Basic Layout -->
<div class="row">
  <div class="col-xl">
    <div class="card mb-4">
      <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Pay to a worker</h5>
      </div>
      <div class="card-body">
        <span id="payWorkerErr"></span>
        <form autocomplete="off" autocomplete="off" id="payWorkerForm">
          <div class="mb-3">
            <label class="form-label" for="select_box">Worker</label>
            <select class="" id="select_box" aria-label="Default select example" required>
                <option selected value="">Select worker</option>
              </select>
          </div>

          <div class="mb-3">
            <label class="form-label" for="amount">Salary Amount</label>
            <input name="amount" type="number" class="form-control" id="amount" placeholder=""  oninvalid="this.setCustomValidity(`Enter salary amount!`)" oninput="this.setCustomValidity('')" required/>
          </div>
          
          <button type="submit" class="btn btn-primary">Pay worker</button>
        </form>
      </div>
    </div>
  </div>
  <div class="col-xl">
    <div class="card mb-4">
      <div class="card-body">
        <span id="payWorkersErr"></span>
        <form autocomplete="off" id="payWorkersForm">
          <div class="mb-3">
            <span class=""> Pay worker with the salary amount provided when registering them.</span>
          </div>
          
          <button type="submit" class="btn btn-primary">Pay</button>
        </form>
      </div>
    </div>
  </div>
</div>

            
          </div>
          <!-- / Content -->

          
          

<!-- Footer -->
  <?php include  $_SERVER['DOCUMENT_ROOT'].'/views/components/footer.phtml'; ?>
<!-- / Footer -->

          
          <div class="content-backdrop fade"></div>
        </div>
        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    
    
    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
    
    
  </div>
  <!-- / Layout wrapper -->

  

  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="/views/assets/vendor/libs/jquery/jquery.js"></script>
  <script src="/views/assets/vendor/libs/popper/popper.js"></script>
  <script src="/views/assets/vendor/js/bootstrap.js"></script>
  <script src="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  
  <script src="/views/assets/vendor/js/menu.js"></script>
  <!-- endbuild -->

  <!-- Vendors JS -->
  
  

  <!-- Main JS -->
  <script src="/views/assets/js/main.js"></script>
  <script src="/views/api/salaries.API.js"></script>
  <script src="/views/dselect.js"></script>

  
</body>


<!-- Mirrored from demos.themeselection.com/sneat-bootstrap-html-admin-template-free/html/form-layouts-vertical.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 26 Dec 2022 09:09:29 GMT -->
</html>
