<!DOCTYPE html>
<html lang="en" class="light-style  customizer-hide" dir="ltr" data-theme="theme-default" data-assets-path="/views/assets/" data-template="vertical-menu-template-free">

  
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>Change Password - <?php echo Settings::$getSiteName ? Settings::$getSiteName : ''?></title>
    
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="/uploads/logos/<?php echo Settings::$getLogo ? Settings::$getLogo : ''?>" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com/">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&amp;display=swap" rel="stylesheet">

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="/views/assets/vendor/fonts/boxicons.css" />
    
    

    <!-- Core CSS -->
    <link rel="stylesheet" href="/views/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="/views/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="/views/assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />
    
    

    <!-- Page CSS -->
    <!-- Page -->
<link rel="stylesheet" href="/views/assets/vendor/css/pages/page-auth.css">
    <!-- Helpers -->
    <script src="/views/assets/vendor/js/helpers.js"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="/views/assets/js/config.js"></script>

    <!-- Custom notification for demo -->
    <!-- beautify ignore:end -->

</head>

<body>

  <!-- Content -->

<div class="container-xxl">
  <div class="authentication-wrapper authentication-basic container-p-y">
    <div class="authentication-inner py-4">

      <!-- Forgot Password -->
      <div class="card">
        <div class="card-body">
          <!-- Logo -->
          <div class="app-brand justify-content-center">
            <a href="index-2.html" class="app-brand-link gap-2">
              <span class="app-brand-text demo text-body fw-bolder"><?php echo Settings::$getSiteName ? Settings::$getSiteName : ''?></span>
            </a>
          </div>
          <!-- /Logo -->
          <p class="mb-4">You are using a default password, for security reasons you are required to set a new password before you can access your account.</p>
          <form id="passwordForm" class="mb-3">
          <span id="settingsErr"></span>
            <div class="mb-3">
              <label for="newPass" class="form-label">New Password</label>
              <input type="password" class="form-control" id="newPass" name="newPass" placeholder="Enter your New Password" autofocus>
            </div>
            <div class="mb-3">
              <label for="conPass" class="form-label">Confirm Password</label>
              <input type="password" class="form-control" id="conPass" name="conPass" placeholder="Enter your Confirm Password" autofocus>
            </div>
            <button type="submit" class="btn btn-primary d-grid w-100">Set Password</button>
          </form>
          <div class="text-center">
            <a href="/logout" class="d-flex align-items-center justify-content-center">
              <i class="bx bx-chevron-left scaleX-n1-rtl bx-sm"></i>
              Logout
            </a>
          </div>
        </div>
      </div>
      <!-- /Forgot Password -->
    </div>
  </div>
</div>

<!-- / Content -->
  <script src="/views/api/login.API.js"></script>


  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="/views/assets/vendor/libs/jquery/jquery.js"></script>
  <script src="/views/assets/vendor/libs/popper/popper.js"></script>
  <script src="/views/assets/vendor/js/bootstrap.js"></script>
  <script src="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  
  <script src="/views/assets/vendor/js/menu.js"></script>
  <!-- endbuild -->

  <!-- Vendors JS -->
  
  

  <!-- Main JS -->
  <script src="/views/assets/js/main.js"></script>

  <!-- Page JS -->
  
</body>


<!-- Mirrored from demos.themeselection.com/sneat-bootstrap-html-admin-template-free/html/auth-forgot-password-basic.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 26 Dec 2022 09:09:13 GMT -->
</html>
