<footer class="content-footer footer bg-footer-theme">
  <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
    <div class="mb-2 mb-md-0">
    <?php echo Settings::$getSiteName ? Settings::$getSiteName : ''?> © <script>
      document.write(new Date().getFullYear())
      </script>
      , made with <a href="https://alfrednti.com/" target="_blank" class="footer-link fw-bolder">❤️</a> by  <a href="https://ribedo.org" target="_blank" class="footer-link fw-bolder">Ribedo IT Service</a>
    </div>
    <div>
      
      Template Designed By <a href="https://themeselection.com/" class="footer-link me-4 fw-bolder" target="_blank">ThemeSelection</a>
      
    </div>
  </div>
</footer>