<?php  
if(isset($_SESSION['userRole']) && $_SESSION['userRole'] !== 'superAdmin' && $_SESSION['userRole'] !== 'admin'):
  include  $_SERVER['DOCUMENT_ROOT'].'/views/404.php';
  return;
endif;
 include  $_SERVER['DOCUMENT_ROOT'].'/views/components/header.phtml'; ?>
  
<!-- / Navbar -->

      

      <!-- Content wrapper -->
      <div class="content-wrapper">

        <!-- Content -->
        
          <div class="container-xxl flex-grow-1 container-p-y">
            
            
<h4 class="fw-bold py-3 mb-4">
  <span class="text-muted fw-light">Workers /</span> Worker's Details
</h4>

    <div class="row">
    <div class="col-md-12">
        <ul class="nav nav-pills flex-column flex-md-row mb-3">
        <li class="nav-item"><a class="nav-link active" href="javascript:void(0);"><i class="bx bx-user me-1"></i> Workers's Profile</a></li>
        <li class="nav-item"><a class="nav-link" href="/worker-salary/<?php echo $params[0] ?>"><i class="bx bx-dollar me-1"></i> Workers's salary history</a></li>
        </ul>
        <div class="card mb-4 p-5">
        <h5 class="card-header">Profile Details</h5>
          <p style="margin-left: 30px" class="p-2" id="pError"></p>
        <!-- Account -->
        <form autocomplete="off" id="updateWorkerFrom" enctype="multipart/form-data">
            <div class="card-body">
              <div class="d-flex align-items-start align-items-sm-center gap-4">
                <img src="/uploads/users/<?php echo $worker['data']['photo']; ?>" alt="user-avatar" class="d-block rounded" height="100" width="100" id="uploadedAvatar" />
                <div class="button-wrapper">
                  <label for="upload" class="btn btn-primary me-2 mb-4" tabindex="0">
                    <span class="d-none d-sm-block">Upload worker photo</span>
                    <i class="bx bx-upload d-block d-sm-none"></i>
                    <input type="file" id="upload" name="workerPhoto" class="account-file-input" hidden accept="image/png, image/jpeg" />
                  </label>
                  <button type="button" class="btn btn-outline-secondary account-image-reset mb-4" id="resetPhoto">
                    <i class="bx bx-reset d-block d-sm-none"></i>
                    <span class="d-none d-sm-block">Reset</span>
                  </button>
      
                  <p class="text-muted mb-0">Allowed JPG, GIF or PNG. Max size of 800K</p>
                  <small></small>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col mb-3" id="inputParent">
                <label for="nameBasic" class="form-label">Name</label>
                <input type="text" id="nameBasic" value="<?php echo $worker['data']['fullName']; ?>" name="workerName" class="form-control" placeholder="Enter Name" required>
                 <small></small>
              </div>
            </div>

            <div class="row">
              <div class="col mb-3" id="inputParent">
                <label for="dob" class="form-label">Date Of Birth</label>
                <input type="date" id="dob" name="dob" value="<?php echo $worker['data']['bateOfBirth'] ?>" class="form-control" placeholder="Worker's Date of Birth" required>
                 <small></small>
              </div>
            </div>

            <div class="row">
              <div class="col mb-3" id="selectParent">
                <label for="defaultSelectRole" class="form-label">Worker Role</label>
                <select id="defaultSelectRole" name="workerRole" class="form-select" required>
                  <option value="">select</option>
                  <option <?php echo $worker['data']['userRole'] === 'attendant' ? 'selected' : ''; ?> value="attendant">Attendant</option>
                  <option <?php echo $worker['data']['userRole'] !== 'attendant' ? 'selected' : ''; ?> value="admin">Admin</option>
                </select>
                 <small></small>
              </div>
            </div>

            <div class="row g-2 mb-3">
              <div class="col mb-0" id="inputParent">
                <label for="phone-h" class="form-label">Phone (one)</label>
                <input type="number" name="workerPhone1" value="<?php echo $worker['data']['phoneOne']; ?>" id="phone-h" class="form-control" placeholder="xxxxxxxxxx" required>
                 <small></small>
              </div>
              <div class="col mb-0" id="inputParent">
                <label for="phone-m" class="form-label">Phone (two)</label>
                <input type="number" name="workerPhone2" id="phone-m" value="<?php echo $worker['data']['phoneTwo']; ?>" class="form-control" placeholder="xxxxxxxxxx" required>
                 <small></small>
              </div>
            </div>

            <div class="row g-2 mb-3">
              <div class="col mb-0" id="inputParent">
                <label for="id-number" class="form-label">I.D Card Number</label>
                <input type="text" name="workerId" id="id-number" value="<?php echo $worker['data']['idNumber']; ?>" class="form-control" placeholder="xxxxxxxxxx" required>
                 <small></small>
              </div>
              <div class="col mb-0" id="inputParent">
                <label for="email" class="form-label">Email</label>
                <input type="email" name="workerEmail" value="<?php echo $worker['data']['userEmail']; ?>" id="email" class="form-control" placeholder="xxx@xxxx.xxx" required>
                 <small></small>
              </div>
            </div>

            <div class="row g-2 mb-3">
              <div class="col-6 mb-0" id="inputParent">
                <label for="address" class="form-label">ADDRESS (number, street, building)</label>
                <input type="text" name="workerAddress" value="<?php echo $worker['data']['address']; ?>" id="address" class="form-control" required>
                 <small></small>
              </div>
              <div class="col-3 mb-0" id="inputParent">
                <label for="city" class="form-label">City/Town</label>
                <input type="text" id="city" value="<?php echo $worker['data']['city']; ?>" name="workerCity" class="form-control" required>
                 <small></small>
              </div>
              <div class="col-3 mb-0" id="inputParent">
                <label for="region" class="form-label">Region</label>
                <input type="text" id="region" value="<?php echo $worker['data']['region']; ?>" name="workerRegion" class="form-control" required>
                 <small></small>
              </div>
            </div>

            <div class="col-md mb-3">
              <small class=" fw-semibold">Have you ever been convicted of a crime other than a minor traffic incident? </small>
              <div class="form-check mt-3">
                <input name="crime-radio" class="form-check-input" type="radio" value="yes" id="defaultRadio1" <?php echo $worker['data']['crime'] !== NULL ? 'checked' : ''; ?>>
                <label class="form-check-label" for="defaultRadio1">
                  Yes
                </label>
              </div>
              <div class="form-check">
                <input name="crime-radio" class="form-check-input" type="radio" value="no" id="defaultRadio2" <?php echo $worker['data']['crime'] === NULL ? 'checked' : ''; ?> >
                <label class="form-check-label" for="defaultRadio2">
                  No
                </label>
              </div>
            </div>

            <div id="crimeDiv">
              <?php if($worker['data']['crime'] !== NULL):?>
                <div class="row g-2 mt-2 mb-4">
                  <div class="col-sm-12 mb-1" id="textareaParent">
                    <label for="" class="form-label">If Yes, please explain</label>
                    <textarea type="number" id="explainCrime" name="explainCrime" class="form-control" required><?php echo $worker['data']['crime'] ?></textarea>
                    <small></small>
                  </div>
              </div>
              <?php endif ?>
            </div>

            <div class="row g-2 mb-3">
              <div class="col-sm-3 mb-0" id="selectParent">
                <label for="defaultSelect" class="form-label">EMPLOYMENT TYPE</label>
                <select id="defaultSelect" name="workerEmpType" class="form-select" required>
                  <option value="">select</option>
                  <option <?php echo $worker['data']['employmentType'] === 'full' ? 'selected' : ''; ?> value="full">Full Time</option>
                  <option <?php echo $worker['data']['employmentType'] === 'part' ? 'selected' : ''; ?>  value="part">Part Time</option>
                </select>
                <small></small>
              </div>
              <div class="col-sm-3 mb-0" id="inputParent">
                <label for="applying" class="form-label">POSITION APPLYING FOR</label>
                <input type="text" value="<?php echo $worker['data']['position'] ?>" id="applying" name="workerEmpPosition" class="form-control" required> 
                  <small></small>
              </div>
              <div class="col-sm-3 mb-0" id="inputParent">
                <label for="salary" class="form-label">DESIRED SALARY</label>
                <input type="text" id="salary" value="<?php echo $worker['data']['salary'] ?>" name="workerEmpSalary" class="form-control" required>
                 <small></small>
              </div>
              <div class="col-sm-3 mb-0" id="inputParent">
                <label for="startDate" class="form-label">DATE YOU CAN START</label>
                <input type="date" name="workerStartDate" value="<?php echo $worker['data']['dateToStart'] ?>" id="startDate" class="form-control" required>
                <small></small>
              </div>
            </div>

            <div class="col-md mb-1">
              <p class=" fw-semibold">EDUCATION (starting from the latest):</p>
            </div>

            <div>
              <div id="schoolFieldDiv">
                <?php
                $schoolNames = explode('|', $worker['data']['schoolName']);
                $schoolLocs = explode('|', $worker['data']['schoolLocation']);
                $dateGrads = explode('|', $worker['data']['dateGrad']);
                foreach ($schoolNames as $key => $schoolName):
                  if($key === 0):?>
                  <div class="row g-2 mb-2">
                    <div class="col-sm-5 mb-0" id="inputParent">
                      <label id="schoolNameLabel" for="workerSchName" class="form-label">School Name</label>
                      <input type="text" value="<?php echo $schoolName ?>" id="workerSchName" class="form-control" placeholder="Enter Name" required>
                      <small id="schoolNameErr"></small>
                    </div>
                    <div class="col-sm-4 mb-0" id="inputParent">
                      <label id="schoolLocLabel" for="location" class="form-label">Location</label>
                      <input type="text" value="<?php echo $schoolLocs [$key] ?>" id="workerSchLoc" class="form-control" placeholder="" required>
                      <small id="schoolLocErr"></small>
                    </div>
                    <div class="col-sm-3 mb-2" id="inputParent">
                      <label id="schoolGradLabel" for="grad" class="form-label">Date Graduated</label>
                      <input type="date" value="<?php echo $dateGrads[$key] ?>" id="workerSchGrad" class="form-control" placeholder="" required>
                      <small id="schoolGradErr"></small>
                    </div>
                  </div>
                <?php else: ?>
                  <div class="row g-2 mt-2 mb-2" id="schoolInputDivs">
                    <div class="col-sm-5 mb-0" id="inputParent">
                      <label for="" class="form-label">School Name</label>
                      <input type="text" value="<?php echo $schoolName ?>"  id="workerSchName" class="form-control" placeholder="" required> 
                      <small></small>
                    </div>
                    <div class="col-sm-4 mb-0" id="inputParent">
                      <label for="" class="form-label">Location</label>
                      <input type="text" value="<?php echo $schoolLocs [$key] ?>" id="workerSchLoc" class="form-control" placeholder="" required>
                      <small></small>
                    </div>
                    <div class="col-sm-3 mb-2" id="inputParent">
                      <label for="" class="form-label">Date Graduated</label>
                      <input type="date" value="<?php echo $dateGrads[$key] ?>" id="workerSchGrad" class="form-control" placeholder="" required>
                      <small></small>
                    </div>
                    <div class="col-3 mt-2">
                      <button type="button" id="removeSchool" class="btn btn-danger mb-3"><i class="bx bx-trash"></i></button>
                    </div>
                  </div>
                <?php endif?> 
                <?php endforeach; ?>
              </div>
                <hr>
              <button type="button" id="addSchool" class="btn btn-secondary mb-3">+ Add Another School Field</button>
            </div>

            <div class="col-md mb-1">
              <p class=" fw-semibold">WORK EXPERIENCE:</p>
            </div>
            <div class="col-md mb-3">
              <small class=" fw-semibold">Does the worker has a working experience? </small>
              <div class="form-check mt-3">
                <input name="workingExp-radio" class="form-check-input" type="radio" <?php echo $worker['data']['companyName'] !== NULL ? 'checked' : ''; ?> value="yes" id="defaultRadio3">
                <label class="form-check-label" for="defaultRadio3">
                  Yes
                </label>
              </div>
              <div class="form-check">
                <input name="workingExp-radio" class="form-check-input" <?php echo $worker['data']['companyName'] === NULL ? 'checked' : ''; ?> type="radio" value="no" id="defaultRadio4">
                <label class="form-check-label" for="defaultRadio4">
                  No
                </label>
              </div>
            </div>

            <div id="experienceFieldDiv">
            <?php
             if($worker['data']['companyName'] !== NULL):
                $companyNames = explode('|', $worker['data']['companyName']);
                $periodFroms = explode('|', $worker['data']['periodFrom']);
                $periodTos = explode('|', $worker['data']['periodTo']);
                $companyPositions = explode('|', $worker['data']['companyPosition']);
                $reasons = explode('|', $worker['data']['reason']);
                foreach ($companyNames as $key => $companyName):
                  if($key === 0):?>
                  <div class="row g-2 mb-2">
                    <div class="col-sm-6 mb-0" id="inputParent">
                      <label for="" class="form-label">Company Name</label>
                      <input type="text" id="workerExpCompany" value="<?php echo $companyName ?>" name="workerExpCompany" class="form-control" placeholder="" required>
                      <small></small>
                    </div>
                    <div class="col-sm-3 mb-0" id="inputParent">
                      <label for="" class="form-label">Period (From)</label>
                      <input type="number" id="workerExpFrom" value="<?php echo $periodFroms[$key] ?>" name="workerExpFrom" class="form-control" placeholder="" required>
                      <small></small>
                    </div>
                    <div class="col-sm-3 mb-2" id="inputParent">
                      <label for="" class="form-label">Period (To)</label>
                      <input type="number" id="workerExpTo" value="<?php echo $periodTos[$key] ?>" name="workerExpTo" class="form-control" placeholder="" required>
                      <small></small>
                    </div>
                    <div class="col-sm-12 mb-2" id="inputParent">
                      <label for="" class="form-label">Position</label>
                      <input type="text" id="workerExpPosition" value="<?php echo $companyPositions[$key] ?>" name="workerExpPosition" class="form-control" placeholder="" required>
                      <small></small>
                    </div>
                    <div class="col-sm-12 mb-1" id="textareaParent">
                      <label for="" class="form-label">Reason for Leaving</label>
                      <textarea name="reasonForLeaving" id="reasonForLeaving" class="form-control" required><?php echo $reasons[$key] ?></textarea>
                      <small></small>
                    </div>
                </div> <br />
                <?php else: ?>
                  <div class="row g-2 mt-2 mb-2" id="experienceInputDiv">
                  <div class="col-sm-6 mb-0" id="inputParent">
                      <label for="" class="form-label">Company Name</label>
                      <input type="text" id="workerExpCompany" value="<?php echo $companyName ?>" name="workerExpCompany" class="form-control" placeholder="" required>
                      <small></small>
                    </div>
                    <div class="col-sm-3 mb-0" id="inputParent">
                      <label for="" class="form-label">Period (From)</label>
                      <input type="number" id="workerExpFrom" value="<?php echo $periodFroms[$key] ?>" name="workerExpFrom" class="form-control" placeholder="" required>
                      <small></small>
                    </div>
                    <div class="col-sm-3 mb-2" id="inputParent">
                      <label for="" class="form-label">Period (To)</label>
                      <input type="number" id="workerExpTo" value="<?php echo $periodTos[$key] ?>" name="workerExpTo" class="form-control" placeholder="" required>
                      <small></small>
                    </div>
                    <div class="col-sm-12 mb-2" id="inputParent">
                      <label for="" class="form-label">Position</label>
                      <input type="text" id="workerExpPosition" value="<?php echo $companyPositions[$key] ?>" name="workerExpPosition" class="form-control" placeholder="" required>
                      <small></small>
                    </div>
                    <div class="col-sm-12 mb-1" id="textareaParent">
                      <label for="" class="form-label">Reason for Leaving</label>
                      <textarea name="reasonForLeaving" id="reasonForLeaving" class="form-control" required><?php echo $reasons[$key] ?></textarea>
                      <small></small>
                    <div class="col-3 mt-2">
                        <button type="button" id="removeCompany" class="btn btn-danger mb-3"><i class="bx bx-trash"></i></button>
                    </div>
                    </div>
                </div>
                <?php endif; ?>
                <?php endforeach; ?>
               <button type="button" id="addExp" class="btn btn-secondary mb-3">+ Add Another Experience Field</button>
              <?php endif ?>
            </div>
            <hr>
            <div id="expBtnDiv"></div>

            <div class="row g-2 mb-3">
              <div class="col mb-0">
                <div class="col-sm-12 mb-1" id="textareaParent">
                  <label for="grad" class="form-label">MAJOR SKILLS</label>
                  <textarea type="text" id="reason" name="workerMajorSkills" class="form-control" required><?php echo $worker['data']['majorSkills']; ?></textarea>
                  <small></small>
                </div>
              </div>
            </div>
            
            <div class="modal-footer">
              <button type="submit" id="addWorkerBtn" class="btn btn-primary">Save Changes</button>
            </div>
          </div>
        </div>
        <!-- /Account -->
        </div>
        </form>
    </div>
    </div>
    <script>
      const companyInputsFirst = `
      <div class="row g-2 mb-2">
          <div class="col-sm-6 mb-0" id="inputParent">
            <label for="" class="form-label">Company Name</label>
            <input type="text" id="workerExpCompany" value="<?php echo isset( $companyNames[0]) ?  $companyNames[0] : '' ?>" name="workerExpCompany" class="form-control" placeholder="" required>
            <small></small>
          </div>
          <div class="col-sm-3 mb-0" id="inputParent">
            <label for="" class="form-label">Period (From)</label>
            <input type="number" id="workerExpFrom" value="<?php echo isset( $periodFroms[0]) ? $periodFroms[0] : '' ?>" name="workerExpFrom" class="form-control" placeholder="" required>
            <small></small>
          </div>
          <div class="col-sm-3 mb-2" id="inputParent">
            <label for="" class="form-label">Period (To)</label>
            <input type="number" id="workerExpTo" value="<?php echo isset( $periodTos[0]) ? $periodTos[0] : '' ?>" name="workerExpTo" class="form-control" placeholder="" required>
            <small></small>
          </div>
          <div class="col-sm-12 mb-2" id="inputParent">
            <label for="" class="form-label">Position</label>
            <input type="text" id="workerExpPosition" value="<?php echo isset( $companyPositions[0]) ? $companyPositions[0] : '' ?>" name="workerExpPosition" class="form-control" placeholder="" required>
            <small></small>
          </div>
          <div class="col-sm-12 mb-1" id="textareaParent">
            <label for="" class="form-label">Reason for Leaving</label>
            <textarea name="reasonForLeaving" id="reasonForLeaving" class="form-control" required><?php echo isset( $reasons[0]) ? $reasons[0] : '' ?></textarea>
            <small></small>
          </div>
      </div>
        `
      const crimeTextArea = `
        <div class="row g-2 mt-2 mb-4">
            <div class="col-sm-12 mb-1" id="textareaParent">
              <label for="" class="form-label">If Yes, please explain</label>
              <textarea type="number" id="explainCrime" name="explainCrime" class="form-control" required><?php echo isset($worker['data']['crime']) ? $worker['data']['crime'] : '' ?></textarea>
              <small></small>
            </div>
        </div>
        `;
    </script>
    <script src="/views/newWorker.js"></script>
    <script src="/views/api/workers.API.js"></script>


          <!-- / Content -->

          
          

<!-- Footer -->
<?php include  $_SERVER['DOCUMENT_ROOT'].'/views/components/footer.phtml'; ?>
<!-- / Footer -->

          
          <div class="content-backdrop fade"></div>
        </div>
        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    
    
    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
    
    
  </div>
  <!-- / Layout wrapper -->

  

  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="/views/assets/vendor/libs/jquery/jquery.js"></script>
  <script src="/views/assets/vendor/libs/popper/popper.js"></script>
  <script src="/views/assets/vendor/js/bootstrap.js"></script>
  <script src="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  
  <script src="/views/assets/vendor/js/menu.js"></script>
  <!-- endbuild -->

  <!-- Vendors JS -->
  
  

  <!-- Main JS -->
  <script src="/views/assets/js/main.js"></script>

  <!-- Page JS -->
  <script src="/views/assets/js/pages-account-settings-account.js"></script>
  
</body>


<!-- Mirrored from demos.themeselection.com/sneat-bootstrap-html-admin-template-free/html/pages-account-settings-account.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 26 Dec 2022 09:09:07 GMT -->
</html>
