<?php include  $_SERVER['DOCUMENT_ROOT'].'/views/components/header.phtml'; ?>
<style>
    input:focus:required:invalid {border: 1px solid red;}
    input:required:valid { border: 1px solid #d9dee3; }
    select:focus:required:invalid {border: 1px solid red;}
    select:required:valid { border: 1px solid #d9dee3; }
    textarea:focus:required:invalid {border: 1px solid red;}
    textarea:required:valid { border: 1px solid #d9dee3; }
</style>
  
<!-- / Navbar -->

      

      <!-- Content wrapper -->
      <div class="content-wrapper">

        <!-- Content -->
        
          <div class="container-xxl flex-grow-1 container-p-y">
            
            
<h4 class="fw-bold py-3 mb-4">
  <span class="text-muted fw-light">Forms /</span> Basic Inputs
</h4>

<div class="row">
  <div class="col-md-6">
    <div class="card mb-4">
      <div class="card-body">
      <form  autocomplete="off" id="userDetailsForm">
          <span id="settingsErr"></span>
            <div class="card-body">
                <div class="d-flex align-items-start align-items-sm-center gap-4">
                  <img src="/uploads/users/<?php echo $loggedInUser['photo'] ? $loggedInUser['photo'] : ''?>"" alt="user-avatar" class="d-block rounded" height="100" width="100" id="uploadedAvatar">
                  <div class="button-wrapper">
                    <label for="upload" class="btn btn-primary me-2 mb-4" tabindex="0">
                      <span class="d-none d-sm-block">Upload new photo</span>
                      <i class="bx bx-upload d-block d-sm-none"></i>
                      <input type="file" id="upload" name="photo" class="account-file-input" hidden="" accept="image/png, image/jpeg">
                    </label>
                    <button type="button" class="btn btn-outline-secondary account-image-reset mb-4">
                      <i class="bx bx-reset d-block d-sm-none"></i>
                      <span class="d-none d-sm-block">Reset</span>
                    </button>
        
                    <p class="text-muted mb-0">Allowed JPG, GIF or PNG. Max size of 800K</p>
                  </div>
                </div>
              </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="basic-default-name">Name</label>
            <div class="col-sm-10">
              <input type="text" name="fullName" class="form-control" value="<?php echo $loggedInUser['fullName'] ? $loggedInUser['fullName'] : ''?>" id="basic-default-name" placeholder="" required/>
            </div>
          </div>
          
          <div class="row justify-content-end">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Save</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card mb-4">
      <h5 class="card-header">Change Password</h5>
      <div class="card-body">
        <form autocomplete="off" id="passwordForm">
          <span id="settingsErr"></span>
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="curPass">Current Password</label>
                <div class="col-sm-10">
                <input type="password"  oninvalid="this.setCustomValidity(`Current Password shouldn't be empty!`)" oninput="this.setCustomValidity('')" name="curPass" class="form-control" placeholder="" required/>
                </div>
            </div>
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="newPass">New Password</label>
                <div class="col-sm-10">
                <input type="password"  oninvalid="this.setCustomValidity(`New Password shouldn't be empty!`)" oninput="this.setCustomValidity('')" name="newPass" class="form-control" id="newPass" placeholder="" required/>
                </div>
            </div>
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="conPass">Confirm New Password</label>
                <div class="col-sm-10">
                <input type="password"  oninvalid="this.setCustomValidity(`Confirm Password shouldn't be empty!`)" oninput="this.setCustomValidity('')" name="conPass" class="form-control" id="conPass" placeholder="" required/>
                </div>
            </div>
            <div class="row justify-content-end">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Change Password</button>
                </div>
            </div>
        </form>
      </div>
    </div>
  </div>

  <!-- Form controls -->
  
  <!-- Input Sizing -->
  

  <!-- Default Checkboxes and radios & Default checkboxes and radios -->
  

  

    <!-- File input -->
    
  </div>
</div>

            
          </div>
          <!-- / Content -->

          
          

<!-- Footer -->
<?php include  $_SERVER['DOCUMENT_ROOT'].'/views/components/footer.phtml'; ?>
<!-- / Footer -->

          
          <div class="content-backdrop fade"></div>
        </div>
        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    
    
    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
    
    
  </div>
  <!-- / Layout wrapper -->

  
  

  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="/views/assets/vendor/libs/jquery/jquery.js"></script>
  <script src="/views/assets/vendor/libs/popper/popper.js"></script>
  <script src="/views/assets/vendor/js/bootstrap.js"></script>
  <script src="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  
  <script src="/views/api/profile.API.js"></script>
  <script src="/views/assets/vendor/js/menu.js"></script>

  <!-- Vendors JS -->
  
  

  <!-- Main JS -->
  <script src="/views/assets/js/main.js"></script>
  <script src="/views/assets/js/pages-account-settings-account.js"></script>

  <!-- Page JS -->
  
  
  
</body>


</html>
